name: ls
description: print working directory
runs: 
  using:  "composite"
  steps:  
    - run: echo ${{ github.action_path }}
      shell: bash
    - run: echo $GITHUB_WORKSPACE
      shell: bash
    - run: ls
      shell: bash
      